version: '3'

services:
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "8989:8989"
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ./config/sonarr:/config
      - ./data/videos/tv:/tv
      - ./data/download:/downloads
    depends_on:
      - deluge
  couchpotato:
    image: linuxserver/couchpotato
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "5050:5050"
    volumes:
      - ./config/couchpotato:/config
      - ./data/videos/movies:/movies
      - ./data/download:/downloads
    depends_on:
      - deluge
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
      - "61337:61337"
      - "61337:61337/udp"
    volumes:
      - ./config/deluge:/config
      - ./data/download:/downloads
  muximux:
    image: linuxserver/muximux
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "80:80"
    volumes:
      - ./config/muximux:/config
    depends_on:
      - plex-homebridge
      - deluge
      - sonarr
      - couchpotato
      - htpcmanager
  htpcmanager:
    image: linuxserver/htpcmanager
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "8085:8085"
    volumes:
      - ./config/htpcmanager:/config
    depends_on:
      - plex-homebridge
      - deluge
      - sonarr
      - couchpotato
  cloudcmd:
    image: coderaiser/cloudcmd
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ~:/root
      - ./data:/mnt/fs
  plex-homebridge:
    build:
      context: ./build/homebridge
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
      - "33400:33400"
      - "51826:51826"
      - "51828:51828"
    network_mode: "host"
    volumes:
      - ./config/plex:/config
      - ./data/videos/transcode:/transcode
      - ./data/videos/tv:/data/tv
      - ./data/videos/movies:/data/movies
      - ./data/videos/demo:/data/demo
      - ./config/homebridge:/root/.homebridge
