version: '3'

services:
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config
      - ./data/videos/tv:/tv
      - ./data/download:/downloads
    depends_on:
      - deluge
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - ./data/videos/movies:/movies
      - ./data/download:/downloads
    depends_on:
      - deluge
  lidarr:
    image: linuxserver/lidarr
    restart: unless-stopped
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "8686:8686"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/lidarr:/config
      - ./data/sound/music:/music
      - ./data/download:/downloads
    depends_on:
      - deluge
  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Argentina/Buenos_Aires'
    ports:
      - "3579:3579"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/ombi:/config
    depends_on:
      - sonarr
      - radarr
      - lidarr
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
      - "61337:61337"
      - "61337:61337/udp"
    volumes:
      - ./config/deluge:/config
      - ./data/download:/downloads
  organizr:
    image: lsiocommunity/organizr
    restart: unless-stopped
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "80:80"
    volumes:
      - ./config/organizr:/config
    depends_on:
      - deluge
      - sonarr
      - radarr
      - lidarr
  cloudcmd:
    image: coderaiser/cloudcmd
    restart: unless-stopped
    container_name: cloudcmd
    ports:
      - "8000:8000"
    volumes:
      - ~:/root
      - ./data:/mnt/fs
  emby:
    image: emby/embyserver
    restart: unless-stopped
    container_name: emby
    environment:
      - UID=1000
      - GID=994
      - GIDLIST=91
      - TZ='America/Argentina/Buenos_Aires'
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - ./config/emby:/config
      - ./data/sound:/mnt/sound
      - ./data/videos:/mnt/videos
      - ./data/videos/movies:/mnt/videos/movies
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    links:
      - emby-reg:mb3admin.com
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  emby-reg:
    build: ./build/emby-reg
    restart: unless-stopped
    container_name: mb3admin.com
    ports:
      - "443:443"
      - "808:80"
