version: '3'

services:
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config
      - ./data/videos/tv:/tv
      - ./data/download:/downloads
    depends_on:
      - deluge
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - ./data/videos/movies:/movies
      - ./data/download:/downloads
    depends_on:
      - deluge
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
      - "61337:61337"
      - "61337:61337/udp"
    volumes:
      - ./config/deluge:/config
      - ./data/download:/downloads
  organizr:
    image: lsiocommunity/organizr
    restart: unless-stopped
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=994
    ports:
      - "80:80"
    volumes:
      - ./config/organizr:/config
    depends_on:
      - plex-homebridge
      - deluge
      - sonarr
      - radarr
  cloudcmd:
    image: coderaiser/cloudcmd
    restart: unless-stopped
    container_name: cloudcmd
    ports:
      - "8000:8000"
    volumes:
      - ~:/root
      - ./data:/mnt/fs
  # home-assistant:
  #   image: homeassistant/home-assistant
  #   restart: unless-stopped
  #   ports:
  #     - "8123:8123"
  #   volumes:
  #     - ./config/home-assistant:/config
  #     - /etc/localtime:/etc/localtime:ro
  # openhab:
  #   image: openhab/openhab:2.0.0-amd64
  #   restart: unless-stopped
  #   environment:
  #     - OPENHAB_HTTP_PORT=8080
  #     - OPENHAB_HTTPS_PORT=8443
  #     - USER_ID=1000
  #     - LC_ALL=en_US.UTF-8
  #     - LANG=en_US.UTF-8
  #     - LANGUAGE=en_US.UTF-8
  #   network_mode: "host"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     # - /etc/timezone:/etc/timezone:ro
  #     - ./config/openhab/addons:/openhab/addons
  #     - ./config/openhab/conf:/openhab/conf
  #     - ./config/openhab/userdata:/openhab/userdata
  plex-homebridge:
    build:
      context: ./build/homebridge
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: plex-homebridge
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=994
      - TZ='America/Buenos_aires'
      - DEBUG=*
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
      - "33400:33400"
      - "51826:51826"
      - "51828:51828"
    network_mode: "host"
    volumes:
      - ./config/plex:/config
      - ./data/videos/transcode:/transcode
      - ./data/videos/tv:/data/tv
      - ./data/videos/movies:/data/movies
      - ./data/videos/demo:/data/demo
      - ./config/homebridge:/homebridge-config
  emby:
    image: xataz/emby
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=994
      - TZ='America/Buenos_aires'
    ports:
      - "8096:8096"
    volumes:
      - ./config/emby:/embyData
      - ./data/videos:/Media
      - ./data/videos/movies:/Media/movies
    depends_on:
      - deluge
      - sonarr
      - radarr
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  geneweb:
    image: schuellerf/geneweb
    container_name: geneweb
    restart: unless-stopped
    ports:
      - 2316:2316
      - 2317:2317
    volumes:
      - ./config/geneweb:/genewebData

