homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -34.5744942
  longitude: -58.4230429
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Argentina/Buenos_Aires

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: sonarr
    api_key: 604a4859ccee47579c0cb432024a627f
    host: 192.168.1.2
    monitored_conditions:
      - upcoming
    days: 2

# Text to speech
tts:
  platform: google

group: !include groups.yaml

media_player:
  - platform: yamaha
    host: 192.168.1.3
    source_ignore:
    source_names:
      HDMI4: "TV"
      HDMI5: "Apple TV"
      HDMI6: "HTPC"
      AV5: "Alexa"
  - platform: apple_tv
    host: 192.168.1.6
    login_id: 00000001-f169-ddbc-888f-a78fadaf49e3

notify:
  - name: Telegram
    platform: telegram
    api_key: 355332605:AAGk-hYuwK22OhyQ6mou9703XHIgYsnXY2A
    chat_id: 67838118

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: alex
    password: ruzz8491